# Generated by Django 5.0.4 on 2025-06-22 06:46

import django.core.validators
import organaizer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='*Allowed names contain letters, digits, spaces, and hyphens.', max_length=110, validators=[django.core.validators.MinLengthValidator(2), organaizer.validators.OrganizerValidator()])),
                ('phone_number', models.CharField(error_messages={'unique': 'That phone number is already in use!'}, max_length=15, unique=True)),
                ('secret_key', models.CharField(help_text='*Pick a combination of 4 unique digits.', max_length=4, validators=[organaizer.validators.OrganizerSecretKeyValidator(), django.core.validators.MinLengthValidator(4)])),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
